export const CHANGE_ROOM_SIZE = 'CHANGE_ROOM_SIZE';
export const CHANGE_CABINET_TYPE='CHANGEE_CABINET_TYPE';
export const CHANGE_DRAWER_COUNT='CHANGE_DRAWER_COUNT';
export const CHANGE_CABINET_WIDTH='CHANGE_CABINET_WIDTH';
